(define (problem manual2)
  (:domain blocks)
  (:objects b1 b2 b3 - block)
  (:init
      (on-table b1)
      (on-table b2)
      (on-table b3)
      (clear b1)
      (clear b2)
      (clear b3)
      (handempty)
  )
  (:goal (and
      (on b1 b2)
      (on b2 b3)
      (clear b1)
      (handempty)
  ))
)
